services:
  prometheus:
    image: prom/prometheus:latest
    container_name: monitoring_prometheus
    restart: unless-stopped
    volumes:
      - ./data/prometheus/config:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    expose:
      - "9090"
    networks:
      monitoring:
        ipv4_address: 172.25.0.10

  node-exporter:
    image: prom/node-exporter:latest
    container_name: monitoring_node_exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"
    expose:
      - "9100"
    networks:
      monitoring:
        ipv4_address: 172.25.0.11

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: monitoring_cadvisor
    privileged: true
    restart: unless-stopped
    expose:
      - "8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /proc:/host/proc:ro
      - /dev/disk/:/dev/disk:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      monitoring:
        ipv4_address: 172.25.0.12

  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    restart: unless-stopped
    expose:
      - "3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=MYPASSWORD
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      monitoring:
        ipv4_address: 172.25.0.13

  process-exporter:
    image: ncabatoff/process-exporter:latest
    container_name: monitoring_process_exporter
    restart: unless-stopped
    pid: host
    volumes:
      - ./data/process-exporter/config:/config
    command:
      - "--config.path=/config/process-exporter.yml"
    expose:
      - "9256"
    networks:
      monitoring:
        ipv4_address: 172.25.0.14

volumes:
  prometheus_data:
  grafana_data:

networks:
  monitoring:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24
          gateway: 172.25.0.1
